### ISSUE TITLE
Missing fonts. JasperReport +AWS lambda(java-11)

### ISSUE THREAD

**Issue by Minvay** [corretto/corretto-11#124]
### Describe the bug
JasperFillManager.fillReport method returns error about missing\broken fonts. The bug is very similar with #118, #53. 
```
java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at java.desktop/sun.font.FontManagerFactory$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.FontManagerFactory.getInstance(Unknown Source)
	at java.desktop/sun.java2d.SunGraphicsEnvironment.getFontManagerForSGE(Unknown Source)
	at java.desktop/sun.java2d.SunGraphicsEnvironment.getAvailableFontFamilyNames(Unknown Source)
	at java.desktop/sun.java2d.SunGraphicsEnvironment.getAvailableFontFamilyNames(Unknown Source)
	at java.desktop/sun.java2d.HeadlessGraphicsEnvironment.getAvailableFontFamilyNames(Unknown Source)
	at net.sf.jasperreports.engine.util.JRGraphEnvInitializer.initializeGraphEnv(JRGraphEnvInitializer.java:58)
	at net.sf.jasperreports.engine.fill.BaseReportFiller.<init>(BaseReportFiller.java:136)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.<init>(JRBaseFiller.java:274)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:79)
	at net.sf.jasperreports.engine.fill.JRFiller.createBandReportFiller(JRFiller.java:251)
	at net.sf.jasperreports.engine.fill.JRFiller.createReportFiller(JRFiller.java:272)
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:156)
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:145)
	at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:758)
	at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:1074)
	at com.coople.filemanager.api.FileManagerHandler.getPdf(FileManagerHandler.java:49)
	at com.coople.filemanager.api.FileManagerHandler.handleRequest(FileManagerHandler.java:36)
	at com.coople.filemanager.api.FileManagerHandler.handleRequest(FileManagerHandler.java:28)
	at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder.handle(AmazonLambdaRecorder.java:79)
	at io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler.handleRequest(QuarkusStreamHandler.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	... 26 more
Caused by: java.lang.NullPointerException
	at java.desktop/sun.awt.FontConfiguration.getVersion(Unknown Source)
	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(Unknown Source)
	at java.desktop/sun.awt.FontConfiguration.init(Unknown Source)
	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(Unknown Source)
	at java.desktop/sun.font.SunFontManager$2.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.SunFontManager.<init>(Unknown Source)
	at java.desktop/sun.awt.FcFontManager.<init>(Unknown Source)
	at java.desktop/sun.awt.X11FontManager.<init>(Unknown Source)
	... 30 more
```

### Handler code:
```
package test;

import static net.sf.jasperreports.engine.JasperExportManager.exportReportToPdf;
import static net.sf.jasperreports.engine.JasperFillManager.fillReport;

import java.nio.charset.StandardCharsets;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent;

import lombok.SneakyThrows;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;

public class TestHandler implements RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {

    private static final Logger LOG = LoggerFactory.getLogger(TestHandler.class);

    @Override
    public APIGatewayProxyResponseEvent handleRequest(APIGatewayProxyRequestEvent event, Context context) {
        try {
            return buildPdfResponse(getPdf());
        } catch (Exception e) {
            LOG.error(e.getMessage(), e);
            return buildErrorResponse();
        }
    }

    @SneakyThrows
    private static byte[] buildPdfResponse() {
        JasperReport report = JasperCompileManager.compileReport("test_template.jrxml");
        JasperPrint jasperPrint = fillReport(report, Map.of("TMP_VALUE", "Hello, World!!!"), new JREmptyDataSource());
        return exportReportToPdf(jasperPrint);
    }

    private APIGatewayProxyResponseEvent sendFile(byte[] content) {
        APIGatewayProxyResponseEvent response = new APIGatewayProxyResponseEvent();
        response.setStatusCode(200);
        response.setBody(new String(content, StandardCharsets.UTF_8));
        Map<String, String> headers = Map.of(
                "Content-Type", "application/pdf",
                "Content-Disposition", "attachment; filename=test.pdf",
                "Content-Length", String.valueOf(content.length)
        );
        response.setHeaders(headers);
        return response;
    }

    private APIGatewayProxyResponseEvent buildErrorResponse() {
        APIGatewayProxyResponseEvent response = new APIGatewayProxyResponseEvent();
        response.setStatusCode(500);
        response.setBody("{}");
        return response;
    }
}
```

### Platform information
    OS: [e.g. Amazon Linux 2] 
    Version [e.g. "11.0.1+13-1" (output from "java -version")]

### Additional context
   The same code works fine with java-8.

**Comment by itomashevich** [comment]
Actually, it's a bit strange, but the issue may be solved:
1) Add **fontconfig.properties** to your project with content as follows:
```
version=1
sequence.allfonts=default
```
2) Reference your **fontconfig.properties** as first thing during startup:
```
Properties props = System.getProperties();
props.put("sun.awt.fontconfig", "/var/task/fontconfig.properties");
```
3) Call font system initialization **2 times**. First call will fail with exception
```
        String[] fonts = null;
        try {
            fonts = GraphicsEnvironment
                    .getLocalGraphicsEnvironment()
                    .getAvailableFontFamilyNames();
        } catch (Exception ex) {}

        fonts = GraphicsEnvironment
                .getLocalGraphicsEnvironment()
                .getAvailableFontFamilyNames();

        for (String font : fonts) {
            System.out.println(font);
        }
```
Voila! Work with Jasper as intended then.
But don't forget to provide fonts with your lambda.
**jasperreports_extension**
```
net.sf.jasperreports.extension.registry.factory.fonts=net.sf.jasperreports.engine.fonts.SimpleFontExtensionsRegistryFactory
net.sf.jasperreports.extension.simple.font.families.dejavu=net/sf/jasperreports/fonts/fonts.xml
```
And refer the provided font in template:
```
<style isDefault="true" name="defaultStyle" fontName="DejaVu Sans"></style>
```

**Comment by benty-amzn** [comment]
Thank you for contacting us with this issue. We're glad you've found a workaround, but this does seem like unexpected behavior and we're looking into it.

**Comment by itomashevich** [comment]
@benty-amzn sure
The code
```
147:     GraphicsEnvironment
148:                    .getLocalGraphicsEnvironment()
149:                    .getAvailableFontFamilyNames();  
```
produces
```
java.lang.ClassCastException: class sun.font.CompositeFont cannot be cast to class sun.font.PhysicalFont (sun.font.CompositeFont and sun.font.PhysicalFont are in module java.desktop of
 loader 'bootstrap')
        at java.desktop/sun.font.SunFontManager.getDefaultPhysicalFont(Unknown Source)
        at java.desktop/sun.font.SunFontManager.initialiseDeferredFont(Unknown Source)
        at java.desktop/sun.font.SunFontManager.initialiseDeferredFonts(Unknown Source)
        at java.desktop/sun.font.SunFontManager.loadFonts(Unknown Source)
        at java.desktop/sun.awt.X11FontManager.loadFonts(Unknown Source)
        at java.desktop/sun.font.SunFontManager.loadFontFiles(Unknown Source)
        at java.desktop/sun.font.SunFontManager.getInstalledFontFamilyNames(Unknown Source)
        at java.desktop/sun.java2d.SunGraphicsEnvironment.getAvailableFontFamilyNames(Unknown Source)
        at java.desktop/sun.java2d.SunGraphicsEnvironment.getAvailableFontFamilyNames(Unknown Source)
        at java.desktop/sun.java2d.HeadlessGraphicsEnvironment.getAvailableFontFamilyNames(Unknown Source)
        at org.acme.hibernate.orm.HelloResource.get(HelloResource.java:149) <-- the handler line
```

**Comment by thariqnu-ifm** [comment]
I've been dealing with the same issue for several days. My guess is the lambda for Java 11 doesn't have linux `fontconfig` or `libfontconfig` package on the container. The container for Java 8 may have it, hence the issue doesn't appear there.

`getAvailableFontFamilyNames()` method itself should not throw any exception if no fonts are installed. Instead, it should be able to return an empty list.

**Comment by Minvay** [comment]
Thanks @itomashevich. Finally, font issue was related to the quarkus build plugin.
1. Load fonts, only once!
```
GraphicsEnvironment
                    .getLocalGraphicsEnvironment()
                    .getAvailableFontFamilyNames(); 
```
2. Prepare the `jasperreport_extention.properties` file. Just cope default and add you fonts. Example:
```
net.sf.jasperreports.extension.registry.factory.simple.font.families=net.sf.jasperreports.engine.fonts.SimpleFontExtensionsRegistryFactory
net.sf.jasperreports.extension.simple.font.families.dejavu=net/sf/jasperreports/fonts/fonts.xml

//all default configuration
```
3. Run the following command after the build
```
jar uvf PATH_TO_JAR/function.jar -C PATH_TO_PROPERTY jasperreports_extension.properties
```

**Comment by felipecardozo** [comment]
Is there any update on this issue ? Having same issue when using JasperReports, we are trying to list the fonts available in the internal JVM of the lambda. Result... same exception awt Fonts etcetcetc.

**Comment by xojins** [comment]
Seems like adding the following package would fix the issue we are experiencing:
`apk add --no-cache fontconfig ttf-dejavu `
