### ISSUE TITLE
Usage of Java Advanced Image IO

### ISSUE THREAD

**Issue by dearnani** [corretto/corretto-11#149]
There is a conflict with imageio library with core libraries javax.desktop. The APIs. which are internally using imageio is not accessible with core SDK,  failing if we add imageio library.

Example exception is it expecting the following class in the exception --

com.sun.image.codec.jpeg.ImageFormatException

The complete Exception is on Using aspose API -- 

Error: One factory fails for the operation "jpeg"
Occurs in: javax.media.jai.ThreadSafeOperationRegistry
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javax.media.jai.FactoryCache.invoke(FactoryCache.java:122)
	at javax.media.jai.OperationRegistry.invokeFactory(OperationRegistry.java:1674)
	at javax.media.jai.ThreadSafeOperationRegistry.invokeFactory(ThreadSafeOperationRegistry.java:473)
	at javax.media.jai.registry.RIFRegistry.create(RIFRegistry.java:332)
	at com.sun.media.jai.opimage.StreamRIF.create(StreamRIF.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javax.media.jai.FactoryCache.invoke(FactoryCache.java:122)
	at javax.media.jai.OperationRegistry.invokeFactory(OperationRegistry.java:1674)
	at javax.media.jai.ThreadSafeOperationRegistry.invokeFactory(ThreadSafeOperationRegistry.java:473)
	at javax.media.jai.registry.RIFRegistry.create(RIFRegistry.java:332)
	at javax.media.jai.RenderedOp.createInstance(RenderedOp.java:819)
	at javax.media.jai.RenderedOp.createRendering(RenderedOp.java:867)
	at javax.media.jai.RenderedOp.getColorModel(RenderedOp.java:2242)
	at javax.media.jai.PlanarImage.getAsBufferedImage(PlanarImage.java:2498)
	at javax.media.jai.PlanarImage.getAsBufferedImage(PlanarImage.java:2546)
	at com.aspose.words.internal.zzKA.zzZ(Unknown Source)
	at com.aspose.words.internal.zzL2.zzY(Unknown Source)
	at com.aspose.words.internal.zzL2.zzZ(Unknown Source)
	at com.aspose.words.internal.zzL2.zzY(Unknown Source)
	at com.aspose.words.internal.zzYL.zzZ(Unknown Source)
	at com.aspose.words.internal.zzYL.zzZ(Unknown Source)
	at com.aspose.words.internal.zzYL.<init>(Unknown Source)
	at com.aspose.words.internal.zzYL.<init>(Unknown Source)
	at com.aspose.words.internal.zzYL.<init>(Unknown Source)
	at com.aspose.words.internal.zzYF.zzXR(Unknown Source)
	at com.aspose.words.internal.zzYF.zzQ(Unknown Source)
	at com.aspose.words.internal.zzCF.zzy5(Unknown Source)
	at com.aspose.words.internal.zzCF.zzyv(Unknown Source)
	at com.aspose.words.internal.zzBM.zzW(Unknown Source)
	at com.aspose.words.internal.zzCE.zzZ(Unknown Source)
	at com.aspose.words.internal.zzDI.zzW(Unknown Source)
	at com.aspose.words.internal.zzDK.zzJj(Unknown Source)
	at com.aspose.words.internal.zzBS.zzJj(Unknown Source)
	at com.aspose.words.zzZ1J.zzZos(Unknown Source)
	at com.aspose.words.zzZY1.zzZ(Unknown Source)
	at com.aspose.words.zzZCH.zzZ(Unknown Source)
	at com.aspose.words.Document.zzY(Unknown Source)
	at com.aspose.words.Document.zzZ(Unknown Source)
	at com.aspose.words.Document.zzZ(Unknown Source)
	at com.aspose.words.Document.save(Unknown Source)
	at com.intuit.printservice.util.convertor.impl.AsposeConvertor$CallableImplementation.call(AsposeConvertor.java:128)
	at com.intuit.printservice.util.convertor.impl.AsposeConvertor$CallableImplementation.call(AsposeConvertor.java:112)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: com/sun/image/codec/jpeg/ImageFormatException
	at com.sun.media.jai.codecimpl.JPEGImageDecoder.decodeAsRenderedImage(JPEGImageDecoder.java:46)
	at com.sun.media.jai.opimage.CodecRIFUtil.create(CodecRIFUtil.java:88)
	at com.sun.media.jai.opimage.JPEGRIF.create(JPEGRIF.java:43)
	... 53 more
Caused by: java.lang.ClassNotFoundException: com.sun.image.codec.jpeg.ImageFormatException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:178)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:68)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 56 more
Error: One factory fails for the operation "stream"
Occurs in: javax.media.jai.ThreadSafeOperationRegistry
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javax.media.jai.FactoryCache.invoke(FactoryCache.java:122)
	at javax.media.jai.OperationRegistry.invokeFactory(OperationRegistry.java:1674)
	at javax.media.jai.ThreadSafeOperationRegistry.invokeFactory(ThreadSafeOperationRegistry.java:473)
	at javax.media.jai.registry.RIFRegistry.create(RIFRegistry.java:332)
	at javax.media.jai.RenderedOp.createInstance(RenderedOp.java:819)
	at javax.media.jai.RenderedOp.createRendering(RenderedOp.java:867)
	at javax.media.jai.RenderedOp.getColorModel(RenderedOp.java:2242)
	at javax.media.jai.PlanarImage.getAsBufferedImage(PlanarImage.java:2498)
	at javax.media.jai.PlanarImage.getAsBufferedImage(PlanarImage.java:2546)
	at com.aspose.words.internal.zzKA.zzZ(Unknown Source)
	at com.aspose.words.internal.zzL2.zzY(Unknown Source)
	at com.aspose.words.internal.zzL2.zzZ(Unknown Source)
	at com.aspose.words.internal.zzL2.zzY(Unknown Source)
	at com.aspose.words.internal.zzYL.zzZ(Unknown Source)
	at com.aspose.words.internal.zzYL.zzZ(Unknown Source)
	at com.aspose.words.internal.zzYL.<init>(Unknown Source)
	at com.aspose.words.internal.zzYL.<init>(Unknown Source)
	at com.aspose.words.internal.zzYL.<init>(Unknown Source)
	at com.aspose.words.internal.zzYF.zzXR(Unknown Source)
	at com.aspose.words.internal.zzYF.zzQ(Unknown Source)
	at com.aspose.words.internal.zzCF.zzy5(Unknown Source)
	at com.aspose.words.internal.zzCF.zzyv(Unknown Source)
	at com.aspose.words.internal.zzBM.zzW(Unknown Source)
	at com.aspose.words.internal.zzCE.zzZ(Unknown Source)
	at com.aspose.words.internal.zzDI.zzW(Unknown Source)
	at com.aspose.words.internal.zzDK.zzJj(Unknown Source)
	at com.aspose.words.internal.zzBS.zzJj(Unknown Source)
	at com.aspose.words.zzZ1J.zzZos(Unknown Source)
	at com.aspose.words.zzZY1.zzZ(Unknown Source)
	at com.aspose.words.zzZCH.zzZ(Unknown Source)
	at com.aspose.words.Document.zzY(Unknown Source)
	at com.aspose.words.Document.zzZ(Unknown Source)
	at com.aspose.words.Document.zzZ(Unknown Source)
	at com.aspose.words.Document.save(Unknown Source)
	at com.intuit.printservice.util.convertor.impl.AsposeConvertor$CallableImplementation.call(AsposeConvertor.java:128)
	at com.intuit.printservice.util.convertor.impl.AsposeConvertor$CallableImplementation.call(AsposeConvertor.java:112)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.media.jai.util.ImagingException: All factories fail for the operation "jpeg"
	at javax.media.jai.OperationRegistry.invokeFactory(OperationRegistry.java:1687)
	at javax.media.jai.ThreadSafeOperationRegistry.invokeFactory(ThreadSafeOperationRegistry.java:473)
	at javax.media.jai.registry.RIFRegistry.create(RIFRegistry.java:332)
	at com.sun.media.jai.opimage.StreamRIF.create(StreamRIF.java:102)
	... 44 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javax.media.jai.FactoryCache.invoke(FactoryCache.java:122)
	at javax.media.jai.OperationRegistry.invokeFactory(OperationRegistry.java:1674)
	... 47 more
Caused by: java.lang.NoClassDefFoundError: com/sun/image/codec/jpeg/ImageFormatException
	at com.sun.media.jai.codecimpl.JPEGImageDecoder.decodeAsRenderedImage(JPEGImageDecoder.java:46)
	at com.sun.media.jai.opimage.CodecRIFUtil.create(CodecRIFUtil.java:88)
	at com.sun.media.jai.opimage.JPEGRIF.create(JPEGRIF.java:43)
	... 53 more
Caused by: java.lang.ClassNotFoundException: com.sun.image.codec.jpeg.ImageFormatException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:178)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:68)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 56 more

**Comment by benty-amzn** [comment]
Hi, based on this portion of the stack trace
`Caused by: java.lang.NoClassDefFoundError: com/sun/image/codec/jpeg/ImageFormatException`
it appears that your library is using a class which is no longer present in Java 11 - you may need a newer version of the library.

The `com.sum.image.codec.jpeg` package was removed, see [official release notes](https://www.oracle.com/java/technologies/compatibility.html)

**Comment by dearnani** [comment]
Hi benty-amzn, Many thanks for your kind response, working fine with imageio dependency on java 8. At 11 it is conflicting with core SDK sun.awt.image.ImageException is conflicting with imageIo classes.
