### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005)

### ISSUE THREAD

**Issue by llukatel97** [corretto/corretto-11#286]
### Describe the bug
I have been using gurobi library with Intellij and everything worked fine. All of a sudden I get EXCEPTION_ACCESS_VIOLATION (0xc0000005):

A fatal error has been detected by the Java Runtime Environment:

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffbfc4793dc, pid=7464, tid=12400

JRE version: OpenJDK Runtime Environment Corretto-11.0.16.9.1 (11.0.16.1+9) (build 11.0.16.1+9-LTS)
Java VM: OpenJDK 64-Bit Server VM Corretto-11.0.16.9.1 (11.0.16.1+9-LTS, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
Problematic frame:
C  [gurobi95.dll+0x3893dc]

No core dump will be written. Minidumps are not enabled by default on client versions of Windows

If you would like to submit a bug report, please visit:
 https://github.com/corretto/corretto-11/issues/
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

---------------  S U M M A R Y ------------

Command Line: -javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Educational Edition 2022.1\lib\idea_rt.jar=58763:C:\Program Files\JetBrains\IntelliJ IDEA Educational Edition 2022.1\bin -Dfile.encoding=UTF-8 main.Main

Host: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz, 4 cores, 7G,  Windows 10 , 64 bit Build 19041 (10.0.19041.1889)
Time: Mon Aug 29 23:37:07 2022 Mitteleuropäische Sommerzeit elapsed time: 158.739038 seconds (0d 0h 2m 38s)

I attached the report file for more information: 
[hs_err_pid7464.log](https://github.com/corretto/corretto-11/files/9448237/hs_err_pid7464.log)

**Comment by yftsai** [comment]
Thanks for reporting. We don't have access to gurobi library for further investigation, but would recommend to diagnose with `-Xcheck:jni` to do additional validation on the arguments passed to JNI functions.

**Comment by llukatel97** [comment]
Thank you for the reply. Since am I by no means an advanced coder, I'd be grateful if you could look at the output that -Xcheck:jni produces in my project. If you can extract some useful information out of it, that would be great. Thanks in advance.

OUTPUT:

PS C:\Users\Lukatela\IdeaProjects\route_preserving_RNG> java -Xcheck:jni
WARNING: JNI local refs: 40, exceeds capacity: 39
        at java.lang.System.initProperties(Native Method)
        at java.lang.System.initializeSystemClass(Unknown Source)
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticVoidMethod
Verwendung: java [-options] class [args...]
           (zur Ausführung einer Klasse)
   oder  java [-options] -jar jarfile [args...]
           (zur Ausführung einer JAR-Datei)
wobei options Folgendes umfasst:
    -d32          Verwendet ein 32-Bit-Datenmodell, sofern verfügbar
    -d64          Verwendet ein 64-Bit-Datenmodell, sofern verfügbar
    -server       zur Auswahl der "server" VM
                  Die Standard-VM ist server.

    -cp <Klassensuchpfad von Verzeichnissen und ZIP-/JAR-Dateien>
    -classpath <Klassensuchpfad von Verzeichnissen und ZIP-/JAR-Dateien>
                  Eine durch ; getrennte Liste mit Verzeichnissen, JAR-Archiven
                  und ZIP-Archiven zur Suche nach Klassendateien.
    -D<name>=<value>
                  Legt eine Systemeigenschaft fest
    -verbose:[class|gc|jni]
                  Aktiviert die Verbose-Ausgabe
    -version      Druckt Produktversion und beendet das Programm
    -version:<value>
                  Warnung: Diese Funktion ist veraltet und wird in einer
                  neueren Version entfernt.
                  Erfordert die angegebene Version zur Ausführung
    -showversion  Druckt Produktversion und fährt fort
    -jre-restrict-search | -no-jre-restrict-search
                  Warnung: Diese Funktion ist veraltet und wird in einer
                  neueren Version entfernt.
                  Bezieht private JREs des Benutzers in Versionssuche ein bzw. schließt sie aus
    -? -help      Druckt diese Hilfemeldung
    -X            Druckt Hilfe zu Nicht-Standardoptionen
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  Aktiviert Assertions mit angegebener Granularität
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  Deaktiviert Assertions mit angegebener Granularität
    -esa | -enablesystemassertions
                  Aktiviert Systemassertionen
    -dsa | -disablesystemassertions
                  Deaktiviert Systemassertionen
    -agentlib:<libname>[=<options>]
                  Lädt native Agent Library <libname>, z.B. -agentlib:hprof
                  siehe auch -agentlib:jdwp=help und -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  Lädt native Agent Library nach vollem Pfadnamen
    -javaagent:<jarpath>[=<options>]
                  Lädt Java-Programmiersprachen-Agent, siehe java.lang.instrument
    -splash:<imagepath>
                  Zeigt Startbildschirm mit angegebenem Bild
Weitere Einzelheiten finden Sie unter http://www.oracle.com/technetwork/java/javase/documentation/index.html
PS C:\Users\Lukatela\IdeaProjects\route_preserving_RNG>

**Comment by yftsai** [comment]
The warning messages indicate that there are pending exceptions. I would recommend to investigate and properly handle them first.

**Comment by eastig** [comment]
@llukatel97,
The crash happens in the gurobi library. You need to check it is installed and configured correctly.
I recommend to try to run your application from a command line. 
You can ask the authors of the library for support: https://support.gurobi.com/hc/en-us/community/topics

**Comment by eastig** [comment]
> The warning messages indicate that there are pending exceptions. I would recommend to investigate and properly handle them first.

@llukatel97 
This is not related to the crash. You don't need to investigate it.
