### ISSUE TITLE
java.security.InvalidKeyException: Could not create key" when using the SunPKCS11-NSS-FIPS provider

### ISSUE THREAD

**Issue by sravannsk** [corretto/corretto-11#310]
Hi We recently deployed the rest services in ROcky LInux +Wildfly 27.x + Corretto JDK 11.0.16 and this service trying to connect to the AWS MQ, noticing the CKR_ATTRIBUTE_VALUE_INVALID , which is known issues in OpenJDK but looks that is fixed in the latest, can you please check if the issues fixed on Amazon COrretto JDK

02-22-2023 16:06:07,871 INFO  [stdout] (DefaultMessageListenerContainer-1)      ... 7 more
02-22-2023 16:06:07,871 INFO  [stdout] (DefaultMessageListenerContainer-1) Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_VALUE_INVALID
02-22-2023 16:06:07,871 INFO  [stdout] (DefaultMessageListenerContainer-1)      at sun.security.pkcs11.wrapper.PKCS11.C_CreateObject(Native Method) ~[jdk.crypto.cryptoki:?]
02-22-2023 16:06:07,872 INFO  [stdout] (DefaultMessageListenerContainer-1)      at sun.security.pkcs11.P11SecretKeyFactory.createKey(P11SecretKeyFactory.java:285) ~[jdk.crypto.cryptoki:?]
02-22-2023 16:06:07,872 INFO  [stdout] (DefaultMessageListenerContainer-1)      at sun.security.pkcs11.P11SecretKeyFactory.convertKey(P11SecretKeyFactory.java:191) ~[jdk.crypto.cryptoki:?]
02-22-2023 16:06:07,872 INFO  [stdout] (DefaultMessageListenerContainer-1)      at sun.security.pkcs11.P11SecretKeyFactory.convertKey(P11SecretKeyFactory.java:123) ~[jdk.crypto.cryptoki:?]
02-22-2023 16:06:07,872 INFO  [stdout] (DefaultMessageListenerContainer-1)      at sun.security.pkcs11.P11Mac.engineInit(P11Mac.java:204) ~[jdk.crypto.cryptoki:?]
02-22-2023 16:06:07,872 INFO  [stdout] (DefaultMessageListenerContainer-1)      at javax.crypto.Mac.init(Mac.java:433) ~[?:?]

If your issue is specific to Corretto 11, then you are in the right place. Please proceed with the following.

### To Reproduce
Steps and (source) code to reproduce the behavior.

### Platform information
    OS: [e.g. Amazon Linux 2]
    Version [e.g. "11.0.1+13-1" (output from "java -version")]

### Additional context

For VM crashes, please attach the error report file. By default the file name is `hs_err_pidpid.log`, where pid is the process ID of the process.

**Comment by benty-amzn** [comment]
Hi, the latest version of Corretto 11 is 11.0.18 at this time, so if you're still using 11.0.16 you can try the latest release to see if it resolves your issue. Corretto typically includes all patches from openjdk, so if the issue has been addressed there (do you have the JBS id so we can confirm?) it should be present in Corretto as well.
