### ISSUE TITLE
Exception while creating an excel sheet through amazon corretto jdk 11 in linux

### ISSUE THREAD

**Issue by sailohith123** [corretto/corretto-11#53]
Thank you for taking the time to help improve OpenJDK and Corretto 11.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your issue concerns OpenJDK 11
and is not specific to Corretto 11
we ask that you raise it to the OpenJDK community.
Depending on your contributor status for OpenJDK,
please use the [JDK bug system](https://bugs.openjdk.java.net/) or
the appropriate [mailing list](http://mail.openjdk.java.net/mailman/listinfo)
for the given problem area or [update project](http://mail.openjdk.java.net/mailman/listinfo/jdk-updates-dev).

If your issue is specific to Corretto 11,
then you are in the right place.
Please proceed with the following.

### To Reproduce
Steps and (source) code to reproduce the behavior.

### Platform information
    OS: [e.g. Amazon Linux 2]
    Version [e.g. "11.0.1+13-1" (output from "java -version")]

### Additional context

Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
at java.desktop/java.awt.Font.getFont2D(Font.java:497)
at java.desktop/java.awt.Font.canDisplayUpTo(Font.java:2246)
at java.desktop/java.awt.font.TextLayout.singleFont(TextLayout.java:469)
at java.desktop/java.awt.font.TextLayout.(TextLayout.java:530)
at org.apache.poi.ss.util.SheetUtil.getDefaultCharWidth(SheetUtil.java:273)
at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.(AutoSizeColumnTracker.java:117)
at org.apache.poi.xssf.streaming.SXSSFSheet.(SXSSFSheet.java:82)
at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:674)
at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:695)
at com.toc.olc.rap.monthend.MonthEnd.OperationHNA(MonthEnd.java:753)
at com.toc.olc.rap.monthend.MonthEnd.execute(MonthEnd.java:300)
at com.toc.olc.rap.monthend.MonthEnd.main(MonthEnd.java:230)
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
... 14 more
Caused by: java.lang.NullPointerException
at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:367)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.desktop/sun.font.SunFontManager.(SunFontManager.java:312)
at java.desktop/sun.awt.FcFontManager.(FcFontManager.java:35)
at java.desktop/sun.awt.X11FontManager.(X11FontManager.java:56)
... 19 more

Hi,
Recently, we have upgraded our java version to oracle jdk 1.8 to amazon corretto 11 jdk.
In the code, while we are creating an row in excel sheet from java 11. The above exception is thrown. I am getting this exception only when I am running in linux . In windows it is running fine.

 Can you help me with these issue?
Thanks

**Comment by yoroto** [comment]
The stack trace means that the specific font might not exist. Do you know which font is referred by the application?

**Comment by ziyiluo** [comment]
@sailohith123 ping again. Besides, would you please verify that the JDK you were using is Corretto?  The output of `java -version` in Corretto is usually like `11.0.x+y-LTS`. Also, would you update your JDK to the latest 11.0.5 and verify if it fixes your issue?

**Comment by julian-bieringer** [comment]
We encountered the same issue too.

While running in a container derived from `amazoncorretto:11.0.6` it is working fine.

However, once deployed in AWS Lambda with Runtime Java 11 it throws the same following stack trace:

```
java.lang.InternalError: java.lang.reflect.InvocationTargetException
        at java.desktop/sun.font.FontManagerFactory$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.font.FontManagerFactory.getInstance(Unknown Source)
        at java.desktop/java.awt.Font.getFont2D(Unknown Source)
        at java.desktop/java.awt.Font.getFontName(Unknown Source)
        at java.desktop/java.awt.Font.getFontName(Unknown Source)
        at com.lowagie.text.pdf.PdfGraphics2D.getCachedBaseFont(PdfGraphics2D.java:1005)
        at com.lowagie.text.pdf.PdfGraphics2D.setFont(PdfGraphics2D.java:1000)
        at com.lowagie.text.pdf.PdfGraphics2D.<init>(PdfGraphics2D.java:217)
        at com.lowagie.text.pdf.PdfContentByte.createGraphics(PdfContentByte.java:2814)
     ...
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        ... 42 more
Caused by: java.lang.NullPointerException
        at java.desktop/sun.awt.FontConfiguration.getVersion(Unknown Source)
        at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(Unknown Source)
        at java.desktop/sun.awt.FontConfiguration.init(Unknown Source)
        at java.desktop/sun.awt.X11FontManager.createFontConfiguration(Unknown Source)
        at java.desktop/sun.font.SunFontManager$2.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.font.SunFontManager.<init>(Unknown Source)
        at java.desktop/sun.awt.FcFontManager.<init>(Unknown Source)
        at java.desktop/sun.awt.X11FontManager.<init>(Unknown Source)
        ... 46 more
```

Our specifications in the container:

```
openjdk 11.0.6 2020-01-14 LTS
OpenJDK Runtime Environment Corretto-11.0.6.10.1 (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.6.10.1 (build 11.0.6+10-LTS, mixed mode)
```

So it looks like some setup between the provided container and the container it is running in AWS Lambda is different.

**Comment by kdnilsen** [comment]
We (the Amazon Corretto) team are investigating further.  We will post additional information as we find a resolution.

**Comment by julian-bieringer** [comment]
> We (the Amazon Corretto) team are investigating further. We will post additional information as we find a resolution.

Great! If you need any additional information, please let me know.

**Comment by julian-bieringer** [comment]
Any updates on this? It currently prevents us from migrating our whole project from Lambda Runtime Java 8 to Java 11.

**Comment by pialinag** [comment]
I am facing issue upgrading my application from oracle java 1.8 to corretto jdk8.202.08.2_64bit  and jdk8.212.04.2_64bit.
My app uses activiti, which calls java awt classes to draw its bpmn modelling diagram.
Initially I was getting following NPE :
java.lang.NullPointerException
	sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
	sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
	sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
	sun.font.SunFontManager$2.run(SunFontManager.java:431)

Then I figured out it was the missing font libraries.
1.	Just for the sake of investigation, I created my own fontconfig.properties in corretto jre/lib
 
2.	I also find the fontmanager rpm package, needed by fontconfig, is also installed in my servers:
rpm -qa |grep -i font
fontconfig-2.10.95-10.el7.x86_64
fontpackages-filesystem-1.44-8.el7.noarch

3.	And I copied the following fonts from jdk1.8/jre/lib to corretto jre/lib:
LucidaSansDemiBold.ttf, LucidaBrightDemiBold.ttf, LucidaSansRegular.ttf,LucidaBrightDemiItalic.ttf  ,LucidaTypewriterBold.ttf,LucidaBrightItalic.ttf,LucidaTypewriterRegular.ttf,LucidaBrightRegular.ttf
LucidaTypewriterBoldOblique.ttf,LucidaSansDemiOblique.ttf,LucidaTypewriterOblique.ttf,LucidaSansOblique.ttf
 
Now I see the rectangles and lines in the diagram alright, but the text is not getting displayed.
This is how the awt classes are called to write the text within the rectangles:
AttributedString attributedString = new AttributedString(text);
    attributedString.addAttribute(TextAttribute.FONT, g.getFont());
    attributedString.addAttribute(TextAttribute.FOREGROUND, Color.black);
    AttributedCharacterIterator characterIterator = attributedString.getIterator();
    int currentHeight = 0;
    List<TextLayout> layouts = new ArrayList<TextLayout>();
    String lastLine = null;
    LineBreakMeasurer measurer = new LineBreakMeasurer(characterIterator, g.getFontRenderContext());
    TextLayout layout = null;
    while (measurer.getPosition() < characterIterator.getEndIndex() && currentHeight <= boxHeight) {
      int previousPosition = measurer.getPosition();
      layout = measurer.nextLayout(boxWidth);
      int height = ((Float)(layout.getDescent() + layout.getAscent() + layout.getLeading())).intValue();
      
        layouts.add(layout);
        currentHeight += height;
    }
    int currentY = y + (centered ? ((boxHeight - currentHeight) /2) : 0);
    int currentX = 0;
    for(TextLayout textLayout : layouts) {
      currentY += textLayout.getAscent();
      currentX = x + (centered ? ((boxWidth - ((Double)textLayout.getBounds().getWidth()).intValue()) /2) : 0);
      textLayout.draw(g, currentX, currentY);

I see layout.getDescent(), layout.getAscent(), layout.getLeading() are returning huge numbers(always 240 in my case, whereas with oracle java 1.8, these used to be like getDescent()= 2.347168 layout.getAscent()= 10.45752) 

Do these not work with corretto 8? 
Could you please share some light on how to proceed?

**Comment by pialinag** [comment]
To add: my OS is Linux  3.10.0-514.10.2.el7.x86_64

**Comment by julian-bieringer** [comment]
For now we could bypass it by setting up our own custom fonconfig

```java
  if (!LOCAL_FONT_CONFIG.exists()) {
			logger.trace(LOCAL_FONT_CONFIG.getAbsolutePath() + " does not exist yet");
			try (BufferedWriter writer = new BufferedWriter(new FileWriter(LOCAL_FONT_CONFIG))) {
				writer.write("version=1\nsequence.allfonts=default");
			} catch (IOException e) {
				logger.error("Writing to file " + LOCAL_FONT_CONFIG.getAbsolutePath() + " failed");
			}
		}
		Properties props = System.getProperties();
		props.put("sun.awt.fontconfig", LOCAL_FONT_CONFIG.getAbsolutePath());
```

**Comment by dkuzmenkov17** [comment]
Hi @julian-bieringer ,
could you please tell me if your solution works for lambda runtime java 11 or maybe you have another solution? I have the same problem but looks like there is no solution for it right now

**Comment by julian-bieringer** [comment]
> Hi @julian-bieringer ,
> could you please tell me if your solution works for lambda runtime java 11 or maybe you have another solution? I have the same problem but looks like there is no solution for it right now

Exactly. It runs in AWS Lambda with Runtime Java11 since multiple weeks now like a charm :+1:

**Comment by dkuzmenkov17** [comment]
> > Hi @julian-bieringer ,
> > could you please tell me if your solution works for lambda runtime java 11 or maybe you have another solution? I have the same problem but looks like there is no solution for it right now
> 
> Exactly. It runs in AWS Lambda with Runtime Java11 since multiple weeks now like a charm 👍

Oh, I hope I will find a problem in my code. Thanks for your answer.

**Comment by KVannahme** [comment]
I had the same problem. I went through the stacktrace. In the SheetUtil.java getDefaultCharWidth is called. In case of an internal error as reported by OP you can handle that error when the system property "org.apache.poi.ss.ignoreMissingFontSystem" is set to true. It will return a default char width then instead of rethrowing the error.

So you either set this property to true in your environment or you might add a configuration to your spring application as following: 

`
@Configuration
public class FontConfiguration {
    
    @PostConstruct
    public void setProperty() {
        System.setProperty("org.apache.poi.ss.ignoreMissingFontSystem", "true");
    }

}
`
